### ISSUE TITLE
updating input data size to match texture issue

### ISSUE THREAD

**Issue by djsoapyknuckles** [cj-mills/barracuda-inference-yolox-demo-brp#1]
I'm getting a debug log every frame that corresponds to the error "LoadRawTextureData: not enough data provided (will result in overread)"
This only occurs when UseAsyncGPUReadback is true
![Screenshot 2023-10-23 085325](https://github.com/cj-mills/barracuda-inference-yolox-demo-brp/assets/74217308/668b08a8-873b-49c7-90b7-ecdae9613b82)
No bounding box is rendered and detected objects stays constant at 1

**Comment by cj-mills** [comment]
Hi @djsoapyknuckles,
I'm guessing there is something about Barracuda that causes strange behavior at odd resolutions. 

Some resolutions in "Free Aspect" mode cause the behavior you describe, while the issue does not occur with the "16:9" aspect ratio.

#### Free Aspect:
https://github.com/cj-mills/barracuda-inference-yolox-demo-brp/assets/9126128/7faa27bc-a893-47aa-8730-db6b3faa0c5b

#### 16:9 Aspect
https://github.com/cj-mills/barracuda-inference-yolox-demo-brp/assets/9126128/507887fd-bc22-4888-8e33-b89dc372059d

**Comment by djsoapyknuckles** [comment]
Ahh, I was wondering that - i have a widescreen so i sometimes pull windows out to non typical rarios to make use of the screen... I'll test it out on my end.

Thank you!

**Comment by djsoapyknuckles** [comment]
Issue resolved - that was definitely the problem. I have a widescreen, so occasionally I pull windows out to odd ratios and forget to lock aspect ratio. Thank you for the assistance!
